name = "cerita-basim"
compatibility_date = "2025-05-19"
compatibility_flags = ["nodejs_compat"]

# Pages will auto-detect this, but explicit for local dev
[vars]
SITE_URL = "https://cerita.basim.id"
TURNSTILE_SECRET = ""
RESEND_API_KEY = ""
ADMIN_EMAIL = "basim@cerita.basim.id"
ENCRYPTION_KEY = ""
ENCRYPTION_SALT = ""

[[d1_databases]]
binding = "DB"
database_name = "cerita-basim-db"
database_id = "" # Fill after `wrangler d1 create cerita-basim-db`

[[kv_namespaces]]
binding = "KV"
id = "" # Fill after `wrangler kv namespace create CERITA_BASIM_KV`

[[r2_buckets]]
binding = "R2"
bucket_name = "cerita-basim-assets"
