name = "cerita-basim"
compatibility_date = "2025-05-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
SITE_URL = "https://cerita.basim.id"
ADMIN_EMAIL = "basim@cerita.basim.id"

[[d1_databases]]
binding = "DB"
database_name = "cerita-basim-db"
database_id = "3019e117-c519-487d-bc05-e68e7bafef67"

[[kv_namespaces]]
binding = "KV"
id = "97d6c3df93b4476399d5e1bc4485dc0d"

[[r2_buckets]]
binding = "R2"
bucket_name = "cerita-basim-assets"
